---
version: "3.4"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    platform: linux/amd64
    build:
      dockerfile: ./compose/local/django/Dockerfile
    image: scram_local_django
    volumes:
      - $CI_PROJECT_DIR:/app:z
      - /tmp/profile_data:/tmp/profile_data
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=scram
      - POSTGRES_USER=scram
      - POSTGRES_PASSWORD=scram
      - DJANGO_READ_DOT_ENV_FILE=True
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DJANGO_SECRET_KEY=DJANGO_SECRET_KY
      - DJANGO_ADMIN_URL=admin/
      - DJANGO_ALLOWED_HOSTS=django
      - DJANGO_SECURE_SSL_REDIRECT=True
      - DJANGO_SERVER_EMAIL=test@test.com
      - WEB_CONCURRENCY=4
      - SCRAM_AUTH_METHOD=local
      - POSTGRES_SSL=False
      - REDIS_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://django:8000/process_expired/"]
    ports:
      - "8000"
      - 3000:3000

  postgres:
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=scram
      - POSTGRES_USER=scram
      - POSTGRES_PASSWORD=scram

  docs:
    image: scram_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    networks:
      default: {}
    volumes:
      - $CI_PROJECT_DIR/docs:/docs:z
      - $CI_PROJECT_DIR/config:/app/config:z
      - $CI_PROJECT_DIR/scram:/app/scram:z
    ports:
      - "7000"
    command: /start-docs

  redis:
    ports:
      - "6379"

  gobgp:
    volumes:
      - $CI_PROJECT_DIR/gobgp_config:/config:z
    ports:
      - "179"
      - "50051"

  translator:
    volumes:
      - ./translator/tests/:/app/tests/
    ports:
      - 3001:3001
    entrypoint: python3
    command: "-m debugpy --listen 0.0.0.0:3001 translator.py"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 0200:c0:ff:ee::/64
