---
version: '3.4'

#
# environmental variables are defined in the .env file in this repo root
#

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  production_redis_data: {}
  production_nginx: {}
  staticfiles:

services:
  # Rework based on known dependencies and podman serial startup
  gobgp:
    volumes:
      - $CI_PROJECT_DIR/gobgp_config:/config:z
    cap_add: [ "CAP_NET_BIND_SERVICE" ]
    networks:
      default: {}
      peering:
        ipv4_address: ${SCRAM_V4_ADDRESS}
        ipv6_address: ${SCRAM_V6_ADDRESS}
    privileged: true
    ports:
      #- "179"
      - "50051"

  redis:
    volumes:
      - production_redis_data:/var/lib/redis:Z

  postgres:
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:z
      - local_postgres_data_backups:/backups:z
    configs:
      file: .envs/.production/.postgres
    #ports:
    #  - "5432:5432"

  django:
    build:
      dockerfile: ./compose/production/django/Dockerfile
    image: scram_production_django
    configs:
      file: .envs/.production/.django
    volumes:
      - ./staticfiles:/staticfiles:rw,z
    healthcheck:
      test: ["CMD", "curl", "-f", "http://django:5000/process_expired/"]
    #ports:
    #  - 5000:5000

  translator:
    configs:
      file: .envs/.production/.translator
    networks:
      default: {}

  nginx:
    image: nginx:1.19
    restart: on-failure:5
    depends_on:
      - django
    networks:
      default: {}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/scram/ssl/server.crt:/etc/ssl/server.crt
      - /etc/scram/ssl/server.key:/etc/ssl/server.key
      - ./staticfiles:/staticfiles:rw,z
    ports:
      - "443:443"
      - "80:80"

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 0200:c0:ff:ee::/64
  peering:
    enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: ${SCRAM_PEERING_IFACE}
    ipam:
      driver: default
      config:
        - subnet: ${SCRAM_V4_SUBNET}
          gateway: ${SCRAM_V4_GATEWAY}
        - subnet: ${SCRAM_V6_SUBNET}
          gateway: ${SCRAM_V6_GATEWAY}
