---

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis_data: {}
  production_nginx: {}

services:
  django:
    build:
      dockerfile: ./compose/production/django/Dockerfile
    image: scram_production_django
    logging:
      driver: journald
      options:
          tag: scram-django
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
      - /etc/vault.d/secrets/kv_root_security.env
    volumes:
      - ./staticfiles:/staticfiles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://django:5000/process_updates/"]

  postgres:
    logging:
      driver: journald
      options:
          tag: scram-postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
      - /etc/vault.d/secrets/kv_root_security.env
    deploy:
      replicas: ${POSTGRES_ENABLED:-0}

  nginx:
    image: nginx:1.19
    logging:
      driver: journald
      options:
          tag: scram-nginx
    restart: on-failure:5
    depends_on:
      - django
    networks:
      default: {}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem:/etc/ssl/server.crt
      - /etc/letsencrypt/live/${HOSTNAME}/privkey.pem:/etc/ssl/server.key
      - ./staticfiles:/staticfiles
    ports:
      - "443:443"
      - "80:80"

  redis:
    logging:
      driver: journald
      options:
          tag: scram-redis
    volumes:
      - production_redis_data:/var/lib/redis:Z

  gobgp:
    logging:
      driver: journald
      options:
          tag: scram-gobgp
    volumes:
      - ./gobgp_config:/config:z
    networks:
      default: {}
      peering:
        priority: 1000
        ipv4_address: ${SCRAM_V4_ADDRESS}
        ipv6_address: ${SCRAM_V6_ADDRESS}
    ports:
      - "179:179"
      - "50051"

  translator:
    logging:
      driver: journald
      options:
          tag: scram-translator
    env_file:
      - ./.envs/.production/.translator

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 0200:c0:ff:ee::/64
  peering:
    enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: ${SCRAM_PEERING_IFACE}
    ipam:
      driver: default
      config:
        - subnet: ${SCRAM_V4_SUBNET}
          gateway: ${SCRAM_V4_GATEWAY}
        - subnet: ${SCRAM_V6_SUBNET}
          gateway: ${SCRAM_V6_GATEWAY}
