---

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    platform: linux/amd64
    build:
      dockerfile: ./compose/local/django/Dockerfile
    image: scram_local_django
    volumes:
      - $CI_PROJECT_DIR:/app:z
      - /tmp/profile_data:/tmp/profile_data
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://django:8000/process_expired/"]
    ports:
      - "8000"
      - 56780:56780
    environment:
      # This can be set to either `debugpy` or `pycharm-pydevd` currently.
      - DEBUG=${DEBUG:-}

  postgres:
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    deploy:
      replicas: ${POSTGRES_ENABLED:-1}

  docs:
    image: scram_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    networks:
      default: {}
    volumes:
      - $CI_PROJECT_DIR/docs:/docs:z
      - $CI_PROJECT_DIR/config:/app/config:z
      - $CI_PROJECT_DIR/scram:/app/scram:z
    ports:
      - "7000"
    command: /start-docs

  redis:
    ports:
      - "6379"

  gobgp:
    volumes:
      - $CI_PROJECT_DIR/gobgp_config:/config:z
    ports:
      - "179"
      - "50051"

  translator:
    volumes:
      - ./translator/tests/:/app/tests/
    ports:
      - 56781:56781
    environment:
      # This can be set to either `debugpy` or `pycharm-pydevd` currently.
      - DEBUG=${DEBUG:-}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 0200:c0:ff:ee::/64
