---

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis_data: {}
  production_nginx: {}

services:
  django:
    build:
      dockerfile: ./compose/production/django/Dockerfile
    image: scram_production_django
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
      - path: /etc/vault.d/secrets/kv_root_security.env
        required: false
    volumes:
      - ./staticfiles:/staticfiles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://django:5000/process_expired/"]

  postgres:
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
      - path: /etc/vault.d/secrets/kv_root_security.env
        required: false
    deploy:
      replicas: ${POSTGRES_ENABLED:-0}

  nginx:
    image: nginx:1.19
    restart: on-failure:5
    depends_on:
      - django
    networks:
      default: {}
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      - HOSTNAME=${HOSTNAME}
    volumes:
      # - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem:/etc/ssl/server.crt
      # - /etc/letsencrypt/live/${HOSTNAME}/privkey.pem:/etc/ssl/server.key
      - ./staticfiles:/staticfiles
    ports:
      - "${SCRAM_HTTPS_PORT:-443}:443"
      - "${SCRAM_HTTP_PORT:-80}:80"

  redis:
    volumes:
      - production_redis_data:/var/lib/redis:Z

  gobgp:
    volumes:
      - ./gobgp_config:/config:z
    networks:
      default: {}
      peering:
        ipv4_address: ${SCRAM_V4_ADDRESS:-10.177.99.104}
        ipv6_address: ${SCRAM_V6_ADDRESS:-fd74:7cbd:fe54::2}
    ports:
      - "179:179"
      - "50051"

  translator:
    env_file:
      - ./.envs/.production/.translator

networks:
  default:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 0200:c0:ff:ee::/64
  peering:
    enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: ${SCRAM_PEERING_IFACE:-eth0}
    ipam:
      driver: default
      config:
        - subnet: ${SCRAM_V4_SUBNET:-10.177.99.0/24}
          gateway: ${SCRAM_V4_GATEWAY:-10.177.99.1}
        - subnet: ${SCRAM_V6_SUBNET:-fd74:7cbd:fe54::/48}
          gateway: ${SCRAM_V6_GATEWAY:-fd74:7cbd:fe54::1}
