---

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    platform: linux/amd64
    build:
      dockerfile: ./compose/local/django/Dockerfile
    image: scram_local_django
    volumes:
      - $CI_PROJECT_DIR:/app:z
      - /tmp/profile_data:/tmp/profile_data
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.django-primary
      - ./.envs/.local/.postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://django:8000/process_updates/"]
      interval: 120s
    ports:
      - "8000"
      - 56780:56780
    environment:
      # This can be set to either `debugpy` or `pycharm-pydevd` currently.
      - DEBUG=${DEBUG:-}

  django-secondary:
    platform: linux/amd64
    build:
      dockerfile: ./compose/local/django/Dockerfile
    image: scram_local_django
    volumes:
      - $CI_PROJECT_DIR:/app:z
      - /tmp/profile_data:/tmp/profile_data
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.django-secondary
      - ./.envs/.local/.postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://django-secondary:8000/process_updates/"]
      interval: 120s
    ports:
      - "8000"
      - 56781:56780
    environment:
      # This can be set to either `debugpy` or `pycharm-pydevd` currently.
      - DEBUG=${DEBUG:-}
    deploy:
      replicas: 1

  postgres:
    volumes:
      - local_postgres_data:/var/lib/postgresql:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d scram -U debug"]
    deploy:
      replicas: ${POSTGRES_ENABLED:-1}
    ports:
      - "5432:5432"

  docs:
    image: scram_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    networks:
      default: {}
    volumes:
      - $CI_PROJECT_DIR:/app:z
    ports:
      - "${DOCS_PORT:-8888}"
    command: "mkdocs serve -a 0.0.0.0:${DOCS_PORT:-8888}"

  redis:
    ports:
      - "6379"
    deploy:
      replicas: 2

  gobgp:
    volumes:
      - $CI_PROJECT_DIR/gobgp_config:/config:z
    ports:
      - "179"
      - "50051"
    deploy:
      replicas: 1


  gobgp-secondary:
    volumes:
      - $CI_PROJECT_DIR/gobgp_config:/config:z
    ports:
      - "179"
      - "50051"
    deploy:
      replicas: 1

  translator:
    volumes:
      - ./translator/tests/:/app/tests/
    env_file:
      - ./.envs/.local/.translator
      - ./.envs/.local/.translator-primary
    ports:
      - 56782:56781
    environment:
      # This can be set to either `debugpy` or `pycharm-pydevd` currently.
      - DEBUG=${DEBUG:-}

  translator-secondary:
    volumes:
      - ./translator/tests/:/app/tests/
    env_file:
      - ./.envs/.local/.translator
      - ./.envs/.local/.translator-secondary
    ports:
      - 56783:56781
    environment:
      # This can be set to either `debugpy` or `pycharm-pydevd` currently.
      - DEBUG=${DEBUG:-}
    deploy:
      replicas: 1

  celery-worker:
    volumes:
      - ./scheduler/src/scheduler/:/app/scheduler:ro
    env_file:
      - ./.envs/.local/.celery

  celery-worker-secondary:
    volumes:
      - ./scheduler/src/scheduler/:/app/scheduler:ro
    env_file:
      - ./.envs/.local/.celery-secondary
    deploy:
      replicas: 1

  celery-beat:
    command:
      ["celery", "-A", "scheduler.app:scram_api_scheduler", "beat", "--loglevel=info"]
    env_file:
      - ./.envs/.local/.celery
    environment:
      - DISABLE_PROCESS_UPDATES=False

  celery-beat-secondary:
    command:
      ["celery", "-A", "scheduler.app:scram_api_scheduler", "beat", "--loglevel=info"]
    env_file:
      - ./.envs/.local/.celery-secondary
    environment:
      - DISABLE_PROCESS_UPDATES=False
    deploy:
      replicas: 1

  flower:
    env_file:
      - ./.envs/.local/.celery
    command:
      ["celery", "-A", "scheduler.app:scram_api_scheduler", "flower", "--port=5555"]
    ports:
      - "5555:5555"

  flower-secondary:
    env_file:
      - ./.envs/.local/.celery-secondary
    command:
      ["celery", "-A", "scheduler.app:scram_api_scheduler", "flower", "--port=5555"]
    ports:
      - "5556:5555"
    deploy:
      replicas: 1


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 0200:c0:ff:ee::/64
