# Generated by Django 3.1.7 on 2021-04-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0008_default_block_actiontype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="expiration",
            field=models.DateTimeField(default="9999, 12, 31, tz=timezone.utc"),
        ),
    ]
