# Generated by Django 3.1.7 on 2021-04-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0009_expiration_to_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actiontype",
            name="available",
            field=models.BooleanField(default=True, help_text="Is this a valid choice for new entries?"),
        ),
        migrations.AlterField(
            model_name="actiontype",
            name="name",
            field=models.CharField(help_text="One-word description of the action", max_length=30),
        ),
    ]
