# Generated by Django 3.2.13 on 2023-02-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0024_alter_client_is_authorized"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="UUID",
            new_name="uuid",
        ),
    ]
