# Generated by Django 3.2.13 on 2024-01-06 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0026_alter_client_hostname"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebSocketMessage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("msg_type", models.CharField(max_length=50, verbose_name="The type of the message")),
                (
                    "msg_data",
                    models.JSONField(default=dict, verbose_name="The JSON payload. See also msg_data_route_field."),
                ),
                (
                    "msg_data_route_field",
                    models.CharField(
                        max_length=25,
                        verbose_name="The key in the JSON payload whose value will contain the route being acted on.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebSocketSequenceElement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "order_num",
                    models.SmallIntegerField(
                        default=0,
                        verbose_name="Sequences are sent from the smallest order_num to the highest. Messages with the same order_num could be sent in any order",
                    ),
                ),
                ("verb", models.CharField(choices=[("A", "Add"), ("C", "Check"), ("R", "Remove")], max_length=1)),
                (
                    "action_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="route_manager.actiontype"),
                ),
                (
                    "websocketmessage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="route_manager.websocketmessage"
                    ),
                ),
            ],
        ),
    ]
