# Generated by Django 4.2.17 on 2024-12-24 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "route_manager",
            "0030_alter_entry_comment_alter_entry_expiration_reason_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="expiration",
            field=models.DateTimeField(
                default=datetime.datetime(
                    9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="historicalentry",
            name="expiration",
            field=models.DateTimeField(
                default=datetime.datetime(
                    9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
