# Generated by Django 4.2.18 on 2025-01-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0031_alter_entry_expiration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="originating_scram_instance",
            field=models.CharField(default="originating_scram_instance_default", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalentry",
            name="originating_scram_instance",
            field=models.CharField(
                default="originating_scram_instance_defaulthistorical", max_length=255
            ),
            preserve_default=False,
        ),
    ]
