# Generated by chriscummings and soehlert by hand on 2025-03-21 13:08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0032_entry_originating_scram_instance_and_more"),
    ]

    operations = [
        migrations.RunSQL("UPDATE route_manager_entry SET originating_scram_instance = 'scram_hostname_not_set'"),
        migrations.RunSQL("UPDATE route_manager_historicalentry SET originating_scram_instance = 'scram_hostname_not_set'")
    ]
