# Generated by Django 4.2.28 on 2026-02-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0034_alter_entry_originating_scram_instance_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="historicalactiontype",
            new_name="route_manag_history_ee6aeb_idx",
            old_fields=("history_date", "id"),
        ),
        migrations.RenameIndex(
            model_name="historicalentry",
            new_name="route_manag_history_0a19f0_idx",
            old_fields=("history_date", "id"),
        ),
        migrations.RenameIndex(
            model_name="historicalignoreentry",
            new_name="route_manag_history_6909c5_idx",
            old_fields=("history_date", "id"),
        ),
    ]
