# Generated by Django 4.2.26 on 2025-11-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0035_alter_client_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="hostname",
            new_name="client_name",
        ),
    ]
