# Generated by Django 5.2.17 on 2026-09-28 14:46

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0038_merge_20260310_2137"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatorType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="One-word name, e.g. gobgp",
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\w+$", "Use only letters, numbers, and underscores.", flags=re.ASCII
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actiontype",
            name="payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Extra data sent with every message for this action, e.g. {"asn": 65550, "community": 666}',
            ),
        ),
        migrations.AddField(
            model_name="historicalactiontype",
            name="payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Extra data sent with every message for this action, e.g. {"asn": 65550, "community": 666}',
            ),
        ),
        migrations.AlterField(
            model_name="actiontype",
            name="name",
            field=models.CharField(
                help_text="One-word description of the action",
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\w+$", "Use only letters, numbers, and underscores.", flags=re.ASCII
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalactiontype",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="One-word description of the action",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\w+$", "Use only letters, numbers, and underscores.", flags=re.ASCII
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="actiontype",
            name="translator_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which translator types actually perform this action",
                to="route_manager.translatortype",
            ),
        ),
    ]
