# Generated by Django 5.2.17 on 2026-09-28 14:46

from django.db import migrations


def copy_websocket_messages(apps, schema_editor):
    """Link every actiontype that had an Add message to gobgp, and keep its payload overrides."""
    ActionType = apps.get_model("route_manager", "ActionType")
    TranslatorType = apps.get_model("route_manager", "TranslatorType")
    WebSocketSequenceElement = apps.get_model("route_manager", "WebSocketSequenceElement")

    gobgp, _ = TranslatorType.objects.get_or_create(name="gobgp")
    # Old code sent every Add in order and GoBGP kept the last path, so the last element wins here too.
    elements = WebSocketSequenceElement.objects.filter(verb="A").order_by("order_num", "pk")
    for element in elements.select_related("websocketmessage"):
        msg = element.websocketmessage
        actiontype = ActionType.objects.get(pk=element.action_type_id)
        actiontype.translator_types.add(gobgp)
        actiontype.payload = {k: v for k, v in msg.msg_data.items() if k != msg.msg_data_route_field}
        actiontype.save(update_fields=["payload"])


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0039_translatortype"),
    ]

    operations = [
        migrations.RunPython(copy_websocket_messages, migrations.RunPython.noop),
    ]
