# Generated by Django 5.2.17 on 2026-10-02 19:58

import django.core.validators
import django.db.models.deletion
import re
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0040_copy_websocket_messages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="websocketsequenceelement",
            name="websocketmessage",
        ),
        migrations.RemoveField(
            model_name="websocketsequenceelement",
            name="action_type",
        ),
        migrations.CreateModel(
            name="HistoricalActionType_translator_types",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "m2m_history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actiontype",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="route_manager.actiontype",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="route_manager.historicalactiontype",
                    ),
                ),
                (
                    "translatortype",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="route_manager.translatortype",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalActionType_translator_types",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTranslatorType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="One-word name, e.g. gobgp",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\w+$",
                                "Use only letters, numbers, and underscores.",
                                flags=re.RegexFlag["ASCII"],
                            )
                        ],
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical translator type",
                "verbose_name_plural": "historical translator types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.DeleteModel(
            name="WebSocketMessage",
        ),
        migrations.DeleteModel(
            name="WebSocketSequenceElement",
        ),
        migrations.AddIndex(
            model_name="historicaltranslatortype",
            index=models.Index(
                fields=["history_date", "id"], name="route_manag_history_286b32_idx"
            ),
        ),
    ]
