# Generated by Django 5.2.17 on 2026-10-06 17:24

import django.db.models.deletion
import netfields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "route_manager",
            "0041_remove_websocketsequenceelement_websocketmessage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowspecRoute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    netfields.fields.CidrAddressField(max_length=43, unique=True),
                ),
                ("source_port", models.PositiveIntegerField()),
                (
                    "destination",
                    netfields.fields.CidrAddressField(max_length=43, unique=True),
                ),
                ("destination_port", models.PositiveIntegerField()),
                ("protocol", models.PositiveIntegerField()),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="entry",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="route_manager.route",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="flowspec_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="route_manager.flowspecroute",
            ),
        ),
        migrations.AddField(
            model_name="historicalentry",
            name="flowspec_route",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="route_manager.flowspecroute",
            ),
        ),
    ]
