# Generated by Django 3.1.7 on 2021-03-10 22:20

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", netfields.fields.InetAddressField(max_length=39)),
            ],
        ),
    ]
