# Generated by Django 3.1.7 on 2021-03-10 22:20

from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', netfields.fields.InetAddressField(max_length=39)),
            ],
        ),
    ]
