# Generated by Django 3.1.7 on 2021-04-08 04:13

from django.db import migrations, models
import netfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0002_ipaddress_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', netfields.fields.InetAddressField(max_length=39, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
