# Generated by Django 3.1.7 on 2021-04-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0004_actiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiontype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='route_manager.actiontype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='route_manager.route')),
            ],
        ),
    ]
