# Generated by Django 3.1.7 on 2021-04-13 20:46

from django.db import migrations


def create_block_actiontype(apps, schema_editor):
    ActionType = apps.get_model('route_manager', 'ActionType')
    block = ActionType(name="block")
    block.save()


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0007_history_expiration'),
    ]

    operations = [
        migrations.RunPython(create_block_actiontype),
    ]
