# Generated by Django 3.1.7 on 2021-04-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0008_auto_20210413_1842'),
        ('route_manager', '0008_auto_20210413_2137'),
    ]

    operations = [
    ]
