# Generated by Django 3.1.7 on 2021-04-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0009_merge_20210414_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='expiration_reason',
            field=models.CharField(blank=True, help_text='Optional reason for the expiration', max_length=200, null=True),
        ),
    ]
