# Generated by Django 3.1.7 on 2021-04-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0011_history_helptext'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('route', 'actiontype')},
        ),
    ]
