# Generated by Django 3.1.7 on 2021-04-20 21:42

from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0012_unique_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route',
            field=netfields.fields.CidrAddressField(max_length=43, unique=True),
        ),
    ]
