# Generated by Django 3.1.7 on 2021-11-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0014_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
