# Generated by Django 3.1.7 on 2021-12-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0015_entry_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="expiration",
            field=models.DateTimeField(default="9999-12-31 00:00Z"),
        ),
    ]
