# Generated by Django 3.2.13 on 2022-07-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0017_ignorelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IgnoreList',
            new_name='IgnoreEntry',
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='ignoreentry',
            options={'verbose_name_plural': 'Ignored Entries'},
        ),
    ]
