# Generated by Django 3.2.13 on 2022-09-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_manager', '0020_historicalactiontype_historicalentry_historicalignoreentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalentry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
