# Generated by Django 4.2.20 on 2025-03-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0033_fix_broken_entry_model_historical_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="originating_scram_instance",
            field=models.CharField(default="scram_hostname_not_set", max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalentry",
            name="originating_scram_instance",
            field=models.CharField(default="scram_hostname_not_set", max_length=255),
        ),
    ]
