# Generated by Django 4.2.20 on 2025-03-25 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0034_alter_entry_originating_scram_instance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalentry",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="entry_history",
                to="route_manager.entry",
            ),
            preserve_default=False,
        ),
    ]
