# Generated by Django 4.2.26 on 2025-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("route_manager", "0036_rename_hostname_client_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="registered_from_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
