# Generated by Django 4.2.29 on 2026-03-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "route_manager",
            "0035_rename_historicalactiontype_history_date_id_route_manag_history_ee6aeb_idx_and_more",
        ),
        ("route_manager", "0037_unique_client_uuid"),
    ]

    operations = []
