name: Run ruff

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yaml') }}

      - name: Install dependencies
        run: pip install ruff

      - name: Fail if we have any style errors
        run: ruff check

      - name: Fail if the code is not formatted correctly (like Black)
        run: ruff format --diff
